### ISSUE TITLE
lost scrolling with Kodi 18

### ISSUE THREAD

**Issue by AJErazzor** [sualfred/script.screensaver.ftvscreensaver#1]
lost scrolling with Kodi 18 - images still change but no scrolling or tile size changes

**Comment by sualfred** [comment]
No support for Kodi 18, because it's buggy as hell from the GUI side. Nearly all my animations are messed up in my skins.

**Comment by Hitcher** [comment]
@sualfred want to give this build a try?

http://mirrors.kodi.tv/test-builds/windows/win32/KodiSetup-20171103-b86ab97-guiscroll-x86.exe

It fixed issues I was having with fTV.

**Comment by AJErazzor** [comment]
Any chance you could do a Linux build?

Thanks
Andrew

**Comment by Hitcher** [comment]
@AJErazzor @sualfred It's just been merged so will hit tomorrows nightly.

**Comment by AJErazzor** [comment]
Hi I’m a numpty with everything where do I need to go to get the files?

Thanks
Andrew

**Comment by Hitcher** [comment]
http://kodi.wiki/view/HOW-TO:Install_Kodi_for_Linux#Installing_a_development_build

**Comment by AJErazzor** [comment]
Ok sorry didn’t know you meant that kind of merge.  I’m running mill house Kodi 18 x86 libreelec dev builds not sure if this would have got the change?  (Cos the latest nightly doesn’t scroll)

Thanks
Andrew

**Comment by Hitcher** [comment]
Ah, now I've looked at the skin code I can see the problem.

`StringCompare` and `IsEmpty` are depreciated in v18 and need to be changed to `String.IsEqual` and `String.IsEmpty` respectively.

@sualfred changing these fixes the problem.

**Comment by AJErazzor** [comment]
Thank you so much I changed those functions and it is back scrolling!!!!!

Thanks
Andrew

**Comment by sualfred** [comment]
Oh, sorry.

Thanks, fixed and pushed the update.
